/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectograficacion_u2;

import java.awt.*;
import java.awt.Graphics;
import java.awt.Polygon;
import java.util.ArrayList;

/**
 *
 * @author ERIKA GARCIA
 */
public class Proyecto_TransformacionesFiguras2D extends javax.swing.JFrame {
    int contador = 0; 
    ArrayList<Polygon> figura = new ArrayList<Polygon>();

    /**
     * Creates new form Proyecto_U2
     */
    public Proyecto_TransformacionesFiguras2D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pizarra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        AjustarE = new javax.swing.JButton();
        CFiguras = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        XT = new javax.swing.JTextField();
        YT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        XE = new javax.swing.JTextField();
        YE = new javax.swing.JTextField();
        Dibujar = new javax.swing.JButton();
        AjustarT = new javax.swing.JButton();
        AjustarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pizarra.setBackground(new java.awt.Color(255, 255, 255));
        Pizarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Pizarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PizarraMouseClicked(evt);
            }
        });
        Pizarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pizarra");
        Pizarra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 8, 396, -1));

        getContentPane().add(Pizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("- Rotación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, -1));

        Borrar.setBackground(new java.awt.Color(204, 204, 255));
        Borrar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        AjustarE.setBackground(new java.awt.Color(204, 204, 255));
        AjustarE.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        AjustarE.setText("Ajustar");
        AjustarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustarEActionPerformed(evt);
            }
        });
        jPanel1.add(AjustarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 50));

        CFiguras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CFigurasItemStateChanged(evt);
            }
        });
        jPanel1.add(CFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 90, 240, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Transformaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 8, 396, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("- Traslación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese el ángulo: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("- Escalamiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 190, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ingrese X:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ingrese Y:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, -1));
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 80, 20));
        jPanel1.add(XT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 20));
        jPanel1.add(YT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, 20));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingrese X:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingrese Y:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, -1));
        jPanel1.add(XE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 80, 20));
        jPanel1.add(YE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 80, 20));

        Dibujar.setBackground(new java.awt.Color(204, 204, 255));
        Dibujar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Dibujar.setText("Dibujar");
        Dibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarActionPerformed(evt);
            }
        });
        jPanel1.add(Dibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        AjustarT.setBackground(new java.awt.Color(204, 204, 255));
        AjustarT.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        AjustarT.setText("Ajustar");
        AjustarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustarTActionPerformed(evt);
            }
        });
        jPanel1.add(AjustarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 50));

        AjustarR.setBackground(new java.awt.Color(204, 204, 255));
        AjustarR.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        AjustarR.setText("Ajustar");
        AjustarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustarRActionPerformed(evt);
            }
        });
        jPanel1.add(AjustarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PizarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PizarraMouseClicked
        if (contador == 0) {
                figura.add(new Polygon());
            }
            figura.get(figura.size() - 1).addPoint(evt.getX(), evt.getY());
            contador++;  
    }//GEN-LAST:event_PizarraMouseClicked

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        figura.clear();
        contador = 0;
        repaint();
        CFiguras.removeAllItems();
        XT.setText("");
        YT.setText("");
        XE.setText("");
        YE.setText("");
        A.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    private void DibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarActionPerformed
       draw(figura.get(figura.size() - 1));
        contador = 0;
        añadeCombo();
    }//GEN-LAST:event_DibujarActionPerformed

    private void AjustarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustarTActionPerformed
         int moveX = Integer.parseInt(XT.getText());
         int moveY = Integer.parseInt(YT.getText());
    
         int index = CFiguras.getSelectedIndex();
    
         int[] puntosX = new int[figura.get(index).npoints];
         int[] puntosY = new int[figura.get(index).npoints];

    for (int i = 0; i < figura.get(index).npoints; i++) {
          puntosX[i] = figura.get(index).xpoints[i] + moveX;
          puntosY[i] = figura.get(index).ypoints[i] + moveY;
    }

         figura.set(index, new Polygon(puntosX, puntosY, figura.get(index).npoints));
         repaint();
    }//GEN-LAST:event_AjustarTActionPerformed
 
    private void AjustarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustarRActionPerformed
        double alpha = Math.toRadians(Double.parseDouble(A.getText()));
        int index = CFiguras.getSelectedIndex();
    
        int[] puntosX = figura.get(index).xpoints.clone();
        int[] puntosY = figura.get(index).ypoints.clone();

        // Calcular centro de rotación como media de las coordenadas
        double centroX = 0;
        double centroY = 0;
    for (int i = 0; i < puntosX.length; i++) {
        centroX += puntosX[i];
        centroY += puntosY[i];
    }
        centroX /= puntosX.length;
        centroY /= puntosY.length;

    for (int i = 0; i < puntosX.length; i++) {
        int x = puntosX[i];
        int y = puntosY[i];

        // Aplicar fórmulas de rotación 
        int newX = (int) ((x - centroX) * Math.cos(alpha) - (y - centroY) * Math.sin(alpha) + centroX);
        int newY = (int) ((x - centroX) * Math.sin(alpha) + (y - centroY) * Math.cos(alpha) + centroY);

        puntosX[i] = newX;
        puntosY[i] = newY;
    }

        figura.set(index, new Polygon(puntosX, puntosY, figura.get(index).npoints));
        repaint();
    }//GEN-LAST:event_AjustarRActionPerformed

    private void AjustarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustarEActionPerformed
        double sx = Double.parseDouble(XE.getText());
        double sy = Double.parseDouble(YE.getText());
        int index = CFiguras.getSelectedIndex();

        int[] puntosX = figura.get(index).xpoints.clone();
        int[] puntosY = figura.get(index).ypoints.clone();

        int centroX = figura.get(index).getBounds().x;
        int centroY = figura.get(index).getBounds().y;

     for (int i = 0; i < puntosX.length; i++) {
        int x = puntosX[i] - centroX;
        int y = puntosY[i] - centroY;

        int newX = centroX + (int) (x * sx);
        int newY = centroY + (int) (y * sy);

        puntosX[i] = newX;
        puntosY[i] = newY;
    }

        figura.set(index, new Polygon(puntosX, puntosY, figura.get(index).npoints));
        repaint();
    }//GEN-LAST:event_AjustarEActionPerformed

    private void CFigurasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CFigurasItemStateChanged
        if(CFiguras.getItemCount() > 0){
            Graphics g = getGraphics();
            g.drawPolygon(figura.get(CFiguras.getSelectedIndex()));
        }
    }//GEN-LAST:event_CFigurasItemStateChanged

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        for(int i = 0; i < figura.size(); i++){
            g.setColor(new Color((int) (Math.random() * 256), (int) (Math.random() * 256), (int) (Math.random() * 256)));
            g.fillPolygon(figura.get(i));
        }
    }
    
    public void draw(Polygon p){
        Graphics g = getGraphics();
        g.setColor(new Color((int) (Math.random() * 256), (int) (Math.random() * 256), (int) (Math.random() * 256)));
        g.fillPolygon(figura.get(figura.size() - 1));
    }
    
    public void añadeCombo() {
        CFiguras.removeAllItems();        
        for (int i = 0; i < figura.size(); i++) {
            CFiguras.addItem("Poligono " + i + " No. Lados: " + figura.get(i).npoints);
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TransformacionesFiguras2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TransformacionesFiguras2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TransformacionesFiguras2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TransformacionesFiguras2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_TransformacionesFiguras2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JButton AjustarE;
    private javax.swing.JButton AjustarR;
    private javax.swing.JButton AjustarT;
    private javax.swing.JButton Borrar;
    private javax.swing.JComboBox<String> CFiguras;
    private javax.swing.JButton Dibujar;
    private javax.swing.JPanel Pizarra;
    private javax.swing.JTextField XE;
    private javax.swing.JTextField XT;
    private javax.swing.JTextField YE;
    private javax.swing.JTextField YT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
